= Aufgaben 1

:idprefix: slide_
:revealjs_slideNumber:
:revealjs_history:

[state=complex]
== Ziel

* Verständnis der GIT Datenstruktur
* Sicherer Umgang mit den Befehlen:
** `git status`
** `git add`, `git rm`, `git mv`
** `git reset`
** `git checkout`
** `git commit`
** `git log`
** `git hist` (== ein Alias)
* Zusatzbefehle
** `git cat-file`, `git ls-tree`, `git show`

== Aufgabe

=== Setup

. Setup GIT
** Windows: 
*** https://git-scm.com/download/win (Git For Windows)
*** http://cmder.net (Full Edition)
** Mac: https://git-scm.com/download/mac
** schön Bunt:
*** https://git-fork.com
*** https://www.sourcetreeapp.com

=== Setup

. Clone Git Repository

----
git clone https://github.com/barclay-reg/dhbw-painground.git
----

=== Übungen 1/2
. Spiele folgende Szenarien durch; nach jedem Szenario sollte `git status` folgenden Text ausgeben "nothing to commit, working tree clean", mit git cat-file und ggf. git ls-tree sollen die Git-Objekte betrachtet werden
.. Erstellen einer neuen Datei (inkl. Inhalt), Hinzufügen zum Index, danach diesen Committen
.. Ändern einer bestehenden Datei (inkl. Inhalt), Hinzufügen zum Index, danach diesen Committen
.. Hinzufügen einer neuen Datei (inkl. Inhalt) in einem Unterordner, Hinzufügen zum Index, Committen

=== Übungen 2/2

* Fortsetzung Szenarien
[start=4]
.. Umbenennen einer bestehenden Datei, Hinzufügen zum Index (Beides, die Löschung und die neue Datei), Committen
.. Ändern einer bestehenden Datei, alte Version der Datei wieder herstellen 
.. Ändern einer bestehenden Datei, Hinzufügen zum Index (nicht committen), Entfernen aus dem Index, Datei nochmals ändern, Hinzufügen zum Index, Committen
.. Ändern einer bestehenden Datei, Hinzufügen zum Index (nicht committen), Datei nochmals ändern, abermals Hinzufügen zum Index, Committen
