= Aufgaben 4

:idprefix: slide_
:revealjs_slideNumber:
:revealjs_history:

[state=complex]
== Ziel

* Verständnis von Remotes, Fetch/Push/Pull, Forks und Clones
* Beherrschen der Befehle
** `git fetch`
** `git pull`
** `git push`
** `git clone`
* Beherrschen des Konzeptes Pull-Request

== Aufgabe

=== Übungen - Vorbereitungen

. Teilt euch in Teams ein (2 pro Team)
.. Registrieren bei https://github.com
.. UserId od. Name PLUS Teammitglied mir mitteilen
. Ich weise euch auf Github einer _Organisation_ zu
. jeder _clont_ (nicht _forken_) das Repository [.lightgreen]#`dhbw-painground`# aus seiner Organisation
** nehmt den Link `https://github.com/...` , *nicht* `git@github.com:...`
** `git clone` in einen Ordner ausführen, der bisher *nicht* mit Git genutzt wurde
** danach in den geklonten Ordner wechseln (mit `cd`)

=== Übungen 1

. Mitglied 1: ändere mehrere Dateien auf `master` und publiziere diese Änderungen, sodass sie auf github sichtbar sind
. Mitglied 2: hole diese Änderungen auf in deine Workcopy
. Mitglied 1 & 2: ändert gleichzeitig mehrere Dateien auf `master` und publiziere diese Änderungen, sodass sie auf github sichtbar sind
. Mitglied 1 & 2: ändert gleichzeitig die gleiche Dateien, die gleiche Zeile auf `master` und publiziere diese Änderungen, sodass sie auf github Sichtbar sind

=== Übungen 2

[.small]
. Mitglied 1 & 2: jeder erstellt (auf github) einen neuen Branch, basierend auf `master` (siehe https://help.github.com/articles/creating-and-deleting-branches-within-your-repository[help.github.com])
. Mitglied 1 & 2: jeder aktiviert lokal seinen erstellten Branch (vorher `git fetch` nötig)
. Mitglied 1 & 2: jeder erstellt mehrere Commits auf seinem Branch und publiziere diese Änderungen, sodass sie auf github sichtbar sind
. Mitglied 1 & 2: gemeinsam - integriert die Änderungen eines Branches auf `master` 
** provoziert einen 3WM per `git merge --no-ff`
. Mitglied 1 & 2: gemeinsam - macht auf dem zweiten Branch einen Rebase auf die neue Spitze von `master` damit ein späterer Merge diese Branches auf `master` mit einem Fast-Forward-Merge erfolgen kann
** führt nach dem Rebase einen Merge auf `master` per `git merge --ff-only` aus

=== Übungen 3

[.small]
. Mitglied 1 & 2: gemeinsam
.. erstellt einen neuen Branch
.. aktiviert lokal diesen erstellten Branch (vorher `git fetch` nötig)
.. erstellt mehrere Commits auf diesem Branch und publiziere diese Änderungen, sodass sie auf github sichtbar sind
. Mitglied 1: erstelle von diesem Branch einen Pull-Request
** siehe https://help.github.com/articles/creating-a-pull-request/
. Mitglied 2: Reviewe diesen Pull-Request, kommentiere ggf. einzelne Änderungen, nachdem alles geklärt wurde, nimm diesen Pull-Request an

== Gruppen

[.small]
. https://github.com/fn-tfe17-g1
. https://github.com/fn-tfe17-g2
. https://github.com/fn-tfe17-g3
. https://github.com/fn-tfe17-g4
. https://github.com/fn-tfe17-g5
. https://github.com/fn-tfe17-g6
. https://github.com/fn-tfe17-g7
. https://github.com/fn-tfe17-g8
. https://github.com/fn-tfe17-g9
. https://github.com/fn-tfe17-g10
. https://github.com/fn-tfe17-g11
. https://github.com/fn-tfe17-g12